import { writeFile } from "node:fs/promises";
import { loadLatestBacktestFeatureCacheForYear } from "@/lib/racing/backtest-cache";
import type { HistoricalTargetRunnerMetricsRow as Row } from "@/lib/racing/historical-target-metrics";

type Year="2025"|"2026"; type Family="combined"|"hurdle"|"chase";
type Context={year:Year;rows:Row[];coverage:string}; type Scores=Map<string,number>; type Eval={year:Year;family:Family;label:string;rows:Row[];scores:Scores;ranks:Map<string,number>};
const OUT="/tmp/jump-rating-confirmation.md", YEARS:Year[]=["2025","2026"], FAMILIES:Family[]=["combined","hurdle","chase"];

async function main(){
  const contexts=await Promise.all(YEARS.map(load));
  const scoreSets=new Map<string,{base:Scores;final:Scores;fallback:Scores;perf:Scores;or:Scores;chaseFinal:Scores}>();
  for(const ctx of contexts) scoreSets.set(ctx.year,buildScores(ctx.rows));
  const evals:Eval[]=[];
  for(const ctx of contexts)for(const family of FAMILIES){const sets=scoreSets.get(ctx.year)!;evals.push(makeEval(ctx,family,"Latest Performance",sets.perf),makeEval(ctx,family,"Official Rating",sets.or),makeEval(ctx,family,"Base 75/25",sets.base),makeEval(ctx,family,"Frozen OR-required",sets.final),makeEval(ctx,family,"Frozen Base fallback",sets.fallback));if(family==="chase")evals.push(makeEval(ctx,family,"Chase Best-L3-Speed alternative",sets.chaseFinal));}
  const leadCuts=leadQuartiles(find(evals,"2025","combined","Frozen Base fallback"));
  const lines:string[]=[];
  lines.push("# Jump Rating Confirmation Study","","Diagnostic only. Jump v4 cache, as-of-safe features, uncapped final-SP evaluation. No production, Research, Today, schema, cache, or saved-rule changes.","");
  definition(lines,leadCuts); coverage(lines,contexts); policies(lines,evals); benchmarks(lines,evals); disagreements(lines,evals); subtypeComparison(lines,evals); chaseAlternative(lines,evals); monthly(lines,evals); field(lines,evals); handicap(lines,evals); orCoverage(lines,contexts); leads(lines,evals,leadCuts); prices(lines,evals); outliers(lines,evals); conclusion(lines,evals);
  await writeFile(OUT,`${lines.join("\n")}\n`,`utf8`); console.log(`Wrote ${OUT}`);
}

async function load(year:Year):Promise<Context>{const cache=await loadLatestBacktestFeatureCacheForYear({family:"jump",year})??await loadLatestBacktestFeatureCacheForYear({family:"all",year});if(!cache)throw new Error(`Missing v4 Jump cache ${year}`);return{year,coverage:`${cache.actualCoverage?.actualFrom??cache.manifest.from} to ${cache.actualCoverage?.actualTo??cache.manifest.to}`,rows:cache.rows.filter(r=>r.features.raceCode==="jump"&&settled(r)).sort(compare)}}

function buildScores(rows:Row[]){const perf=new Map<string,number>(),or=new Map<string,number>(),base=new Map<string,number>(),final=new Map<string,number>(),fallback=new Map<string,number>(),chaseBase=new Map<string,number>(),chaseFinal=new Map<string,number>();for(const race of group(rows,r=>r.features.targetRaceId).values()){
  const pp=percentiles(race,r=>r.features.latestPerformanceRating),sp=percentiles(race,r=>r.features.latestSpeedRating),op=percentiles(race,r=>r.features.officialRating),l3=percentiles(race,r=>r.features.bestSpeedLast3);
  for(const r of race){const k=id(r),p=pp.get(k),s=sp.get(k),o=op.get(k),l=l3.get(k);if(p!==undefined)perf.set(k,p);if(o!==undefined)or.set(k,o);if(p!==undefined&&s!==undefined)base.set(k,.75*p+.25*s);if(p!==undefined&&l!==undefined)chaseBase.set(k,.75*p+.25*l);}
  const bp=percentiles(race,r=>base.get(id(r))??null),cp=percentiles(race,r=>chaseBase.get(id(r))??null);
  for(const r of race){const k=id(r),b=bp.get(k),c=cp.get(k),o=op.get(k);if(b!==undefined){if(o!==undefined)final.set(k,.8*b+.2*o);fallback.set(k,o!==undefined?.8*b+.2*o:b);}if(c!==undefined&&o!==undefined)chaseFinal.set(k,.8*c+.2*o);}
  }return{base,final,fallback,perf,or,chaseFinal};}

function definition(lines:string[],cuts:number[]){lines.push("## Candidate Definition","", "Latest Performance is the as-of latest prior-run performance/RPR-style metric. Latest Speed is the as-of latest prior Jump speed metric. Each is converted within race to a competition-rank percentile (rank 1 = 1; lowest = 0), then Base = 75% Performance + 25% Speed. Base is re-percentiled before Final = 80% Base + 20% OR percentile.","","OR-required rates only runners with all three inputs. Base fallback uses Final when OR exists and Base when OR is missing. No OR imputation. Equal scores share competition rank; missing inputs remain unrated.","",`Lead buckets use 2025 fallback-candidate quartiles, frozen for 2026: ${cuts.map(n=>n.toFixed(4)).join(", ")}.`,"");}
function coverage(lines:string[],contexts:Context[]){lines.push("## Coverage","");table(lines,contexts.flatMap(c=>FAMILIES.map(f=>{const r=familyRows(c.rows,f);return{year:c.year,family:f,coverage:c.coverage,races:distinct(r,x=>x.features.targetRaceId),runners:r.length,"Performance valid":count(r,x=>x.features.latestPerformanceRating!==null),"Speed valid":count(r,x=>x.features.latestSpeedRating!==null),"OR valid":count(r,x=>x.features.officialRating!==null),"missing OR %":pct(rate(count(r,x=>x.features.officialRating===null),r.length))};})));}

function policies(lines:string[],es:Eval[]){lines.push("## Missing-OR Policies","","Policy A (OR-required) and Policy C (explicitly unrated when OR is missing) are operationally identical, so metrics are reported once. Policy B is Base fallback.","");table(lines,es.filter(e=>e.label.startsWith("Frozen")).map(metricRow));}
function benchmarks(lines:string[],es:Eval[]){lines.push("## Matched Benchmark Comparison","","Rows below restrict each comparison to races/runners rated by the frozen policy being evaluated.","");const out:Record<string,unknown>[]=[];for(const y of YEARS)for(const f of FAMILIES)for(const policy of ["Frozen OR-required","Frozen Base fallback"]){const target=find(es,y,f,policy),ids=new Set(target.scores.keys());for(const label of ["Latest Performance","Official Rating","Base 75/25",policy]){const e=find(es,y,f,label),matched=restrict(e,ids);out.push(metricRow(matched));}}table(lines,out);}

function disagreements(lines:string[],es:Eval[]){lines.push("## Pairwise Rank-1 Disagreements","", "Main candidate is Base fallback. Candidate-vs-OR uses races where both have one unambiguous rank-1 selection; tied rank-1 races are excluded.","");table(lines,YEARS.flatMap(y=>[["Latest Performance","performance"],["Official Rating","OR"]].map(([label,short])=>disagreementRow(y,find(es,y,"combined","Frozen Base fallback"),find(es,y,"combined",label!),`Candidate vs ${short}`))));}
function subtypeComparison(lines:string[],es:Eval[]){lines.push("## Hurdles And Chases","");table(lines,es.filter(e=>e.label==="Frozen Base fallback"||e.label==="Latest Performance"||e.label==="Official Rating").filter(e=>e.family!=="combined").map(metricRow));}
function chaseAlternative(lines:string[],es:Eval[]){lines.push("## Chase Alternative","");const metrics:Record<string,unknown>[]=[],comparisons:Record<string,unknown>[]=[];for(const y of YEARS){const main=find(es,y,"chase","Frozen OR-required"),alt=find(es,y,"chase","Chase Best-L3-Speed alternative");metrics.push(metricRow(main),metricRow(alt));comparisons.push(disagreementRow(y,alt,main,"Alternative vs main"));}table(lines,metrics);lines.push("Unambiguous rank-1 disagreement races:","");table(lines,comparisons);}

function monthly(lines:string[],es:Eval[]){lines.push("## Monthly Stability: Base Fallback","");const out:Record<string,unknown>[]=[];for(const e of es.filter(x=>x.label==="Frozen Base fallback"))for(const [m,rows]of group(rank1(e),r=>r.features.raceDate.slice(0,7))){const z=bet(rows);out.push({year:e.year,family:e.family,month:m,selections:rows.length,winners:count(rows,r=>r.outcome.won===true),strike:pct(rate(count(rows,r=>r.outcome.won===true),rows.length)),ROI:pct(z.roi),"A/E":num(z.ae)});}table(lines,out);}
function field(lines:string[],es:Eval[]){lines.push("## Field-Size Stability","");bucketTable(lines,es,"field size",r=>{const n=r.features.actualRunnerCount??r.features.declaredRunnerCount;return n===null?"missing":n<=5?"2-5":n<=8?"6-8":"9+";});}
function handicap(lines:string[],es:Eval[]){lines.push("## Handicap Split","");const out:Record<string,unknown>[]=[];for(const e of es.filter(x=>x.label==="Frozen Base fallback"))for(const [band,rows]of group(e.rows,r=>isHandicap(r)?"handicap":"non-handicap")){const sub=restrictRows(e,rows),m=metric(sub);out.push({year:e.year,family:e.family,band,selections:m.selections,strike:pct(m.strike),"top3 capture":pct(m.top3),"A/E":num(m.ae)});}table(lines,out);}
function orCoverage(lines:string[],contexts:Context[]){lines.push("## OR Coverage Analysis","");const out:Record<string,unknown>[]=[];for(const c of contexts)for(const f of ["hurdle","chase"]as Family[])for(const [type,rows]of group(familyRows(c.rows,f),r=>`${isHandicap(r)?"handicap":"non-handicap"} / ${isNovice(r)?"novice/maiden":"other"}`)){out.push({year:c.year,family:f,type,runners:rows.length,"missing OR":count(rows,r=>r.features.officialRating===null),"missing OR %":pct(rate(count(rows,r=>r.features.officialRating===null),rows.length))});}table(lines,out);}
function leads(lines:string[],es:Eval[],cuts:number[]){lines.push("## Candidate Rank Confidence / Lead","");const out:Record<string,unknown>[]=[];for(const e of es.filter(x=>x.label==="Frozen Base fallback")){const byRunner=leadsByRunner(e);for(const [band,rows]of group(rank1(e).filter(r=>byRunner.has(id(r))),r=>leadBand(byRunner.get(id(r))??null,cuts))){out.push({year:e.year,family:e.family,band,selections:rows.length,winners:count(rows,r=>r.outcome.won===true),strike:pct(rate(count(rows,r=>r.outcome.won===true),rows.length))});}}table(lines,out);}
function prices(lines:string[],es:Eval[]){lines.push("## Final-SP Behaviour","");bucketTable(lines,es,"SP",r=>{const n=sp(r);return n===null?"missing":n<2?"<2.0":n<3?"2.0-2.99":n<5?"3.0-4.99":n<9?"5.0-8.99":"9.0+";});}
function outliers(lines:string[],es:Eval[]){lines.push("## Outlier Stress","");const out:Record<string,unknown>[]=[];for(const e of es.filter(x=>x.label.startsWith("Frozen"))){const rows=rank1(e),b=bet(rows);if((b.roi??-1)<=0)continue;const big=[...rows].filter(r=>r.outcome.won&&sp(r)!==null).sort((a,b)=>(sp(b)??0)-(sp(a)??0))[0];if(!big)continue;const s=bet(rows.filter(r=>id(r)!==id(big)));out.push({year:e.year,family:e.family,policy:e.label,"largest winner":`${big.features.horseName} @ ${sp(big)}`,ROI:pct(b.roi),"stressed ROI":pct(s.roi),"stressed A/E":num(s.ae)});}table(lines,out);}

function conclusion(lines:string[],es:Eval[]){const p=find(es,"2026","combined","Latest Performance"),o=find(es,"2026","combined","Official Rating"),req=find(es,"2026","combined","Frozen OR-required"),fb=find(es,"2026","combined","Frozen Base fallback"),ch=find(es,"2026","chase","Chase Best-L3-Speed alternative"),mainCh=find(es,"2026","chase","Frozen OR-required"),orMatched=restrict(o,new Set(req.scores.keys())),ready=atLeast(metric(fb).strike,metric(p).strike)&&atLeast(metric(req).strike,metric(orMatched).strike);lines.push("## Decision Framework","",`1. Frozen fallback candidate vs Latest Performance in 2026: ${strike(fb)} vs ${strike(p)}.`,`2. On OR-covered populations, candidate vs OR alone: ${strike(req)} vs ${strike(orMatched)}.`,`3. Base fallback is ${metric(fb).ratedRaces>metric(req).ratedRaces?"preferable for coverage":"not needed for coverage"}; strike ${strike(fb)} vs ${strike(req)} (different coverage populations).`,`4. Fallback adds ${metric(fb).ratedRaces-metric(req).ratedRaces} rated races in 2026 combined; see policy table for strike impact.`,`5. Hurdle/chase tables show persistent level and coverage differences; separate final readiness checks remain justified.`,`6. Chase alternative 2026 strike ${strike(ch)} vs main ${strike(mainCh)}; disagreement table determines whether the gain is real winner recovery.`,`7. Monthly results show whether performance is broad or concentrated.`,`8. Fixed field-size bands show whether strength extends beyond small fields.`,`9. ${ready?"The frozen candidate is suitable for a final production-readiness diagnostic.":"No single candidate clears both Performance and OR benchmarks; subtype/coverage behavior remains unresolved."}`,"");}

function metricRow(e:Eval){const m=metric(e);return{year:e.year,family:e.family,candidate:e.label,"rated races":m.ratedRaces,"fully rateable races":m.fullRaces,"runners rated":e.scores.size,"coverage %":pct(rate(e.scores.size,e.rows.length)),"rank1 selections":m.selections,"rank1 winners":m.winners,"rank1 strike":pct(m.strike),"top3 winner capture":pct(m.top3),"top3 place capture":pct(m.top3Place),association:num(m.association),ROI:pct(m.roi),"A/E":num(m.ae)};}
function metric(e:Eval){const one=rank1(e),top=e.rows.filter(r=>(e.ranks.get(id(r))??99)<=3),wins=e.rows.filter(r=>r.outcome.won),places=e.rows.filter(r=>r.outcome.placed),b=bet(one),raceGroups=group(e.rows,r=>r.features.targetRaceId);return{ratedRaces:distinct(e.rows.filter(r=>e.scores.has(id(r))),r=>r.features.targetRaceId),fullRaces:[...raceGroups.values()].filter(rs=>rs.every(r=>e.scores.has(id(r)))).length,selections:one.length,winners:count(one,r=>r.outcome.won===true),strike:rate(count(one,r=>r.outcome.won===true),one.length),top3:rate(count(top,r=>r.outcome.won===true),wins.length),top3Place:rate(count(top,r=>r.outcome.placed===true),places.length),association:association(e),roi:b.roi,ae:b.ae};}
function disagreementRow(year:Year,a:Eval,b:Eval,label:string){const am=uniqueRank1ByRace(a),bm=uniqueRank1ByRace(b);let races=0,aw=0,bw=0,neither=0;for(const race of new Set([...am.keys(),...bm.keys()])){const x=am.get(race),y=bm.get(race);if(!x||!y||id(x)===id(y))continue;races++;if(x.outcome.won)aw++;if(y.outcome.won)bw++;if(!x.outcome.won&&!y.outcome.won)neither++;}return{year,family:a.family,comparison:label,"disagreement races":races,"left winners":aw,"right winners":bw,neither,"net left extra":aw-bw};}
function bucketTable(lines:string[],es:Eval[],context:string,key:(r:Row)=>string){const out:Record<string,unknown>[]=[];for(const e of es.filter(x=>x.label==="Frozen Base fallback"))for(const [band,rows]of group(rank1(e),key)){const b=bet(rows);out.push({year:e.year,family:e.family,context,band,selections:rows.length,strike:pct(rate(count(rows,r=>r.outcome.won===true),rows.length)),ROI:pct(b.roi),"A/E":num(b.ae)});}table(lines,out);}

function makeEval(ctx:Context,family:Family,label:string,scores:Scores):Eval{const rows=familyRows(ctx.rows,family),ids=new Set(rows.map(id)),sub=new Map([...scores].filter(([k])=>ids.has(k)));return{year:ctx.year,family,label,rows,scores:sub,ranks:rank(rows,r=>sub.get(id(r))??null)};} function restrict(e:Eval,ids:Set<string>){return restrictRows(e,e.rows.filter(r=>ids.has(id(r))));} function restrictRows(e:Eval,rows:Row[]):Eval{const ids=new Set(rows.map(id)),scores=new Map([...e.scores].filter(([k])=>ids.has(k)));return{...e,rows,scores,ranks:rank(rows,r=>scores.get(id(r))??null)};}
function familyRows(rows:Row[],f:Family){return f==="combined"?rows:rows.filter(r=>subtype(r)===f);} function subtype(r:Row){const s=`${r.features.raceName} ${r.features.raceType}`.toLowerCase();return/\bhurdles?\b/.test(s)?"hurdle":/\bchase\b|\bsteeplechase\b/.test(s)?"chase":"other";}
function percentiles(rows:Row[],get:(r:Row)=>number|null){const ranks=rank(rows,get),n=ranks.size,out=new Map<string,number>();for(const[k,v]of ranks)out.set(k,n<=1?1:(n-v)/(n-1));return out;} function rank(rows:Row[],get:(r:Row)=>number|null){const out=new Map<string,number>();for(const race of group(rows,r=>r.features.targetRaceId).values()){const a=race.map(r=>({r,v:get(r)})).filter((x):x is{r:Row,v:number}=>valid(x.v)).sort((x,y)=>y.v-x.v||id(x.r).localeCompare(id(y.r)));let pv:number|null=null,pr=0;a.forEach((x,i)=>{const z=x.v===pv?pr:i+1;out.set(id(x.r),z);pv=x.v;pr=z;});}return out;}
function association(e:Eval){const x:number[]=[],y:number[]=[];for(const r of e.rows){const s=e.scores.get(id(r)),p=r.outcome.finishingPosition;if(s!==undefined&&p!==null){x.push(s);y.push(-p);}}return pearson(rankVals(x),rankVals(y));} function rank1(e:Eval){return e.rows.filter(r=>e.ranks.get(id(r))===1);} function strike(e:Eval){return pct(metric(e).strike);}
function bet(rows:Row[]){const r=rows.filter(x=>sp(x)!==null),wins=r.filter(x=>x.outcome.won),ret=wins.reduce((s,x)=>s+sp(x)!,0),ex=r.reduce((s,x)=>s+1/sp(x)!,0);return{roi:rate(ret-r.length,r.length),ae:ex?wins.length/ex:null};} function sp(r:Row){const n=Number(r.outcome.startingPriceDecimal);return Number.isFinite(n)&&n>0?n:null;}
function uniqueRank1ByRace(e:Eval){const out=new Map<string,Row>();for(const[race,rows]of group(rank1(e),r=>r.features.targetRaceId))if(rows.length===1)out.set(race,rows[0]!);return out;} function leadsByRunner(e:Eval){const out=new Map<string,number>();for(const race of group(e.rows.filter(r=>e.scores.has(id(r))),r=>r.features.targetRaceId).values()){const sorted=[...race].sort((a,b)=>e.scores.get(id(b))!-e.scores.get(id(a))!);if(sorted.length>=2)out.set(id(sorted[0]!),e.scores.get(id(sorted[0]!))!-e.scores.get(id(sorted[1]!))!);}return out;} function leadQuartiles(e:Eval){const a=[...leadsByRunner(e).values()].sort((x,y)=>x-y);return[quantile(a,.25),quantile(a,.5),quantile(a,.75)];} function leadBand(v:number|null,c:number[]){return v===null?"missing":v<=c[0]!?"very small":v<=c[1]!?"small":v<=c[2]!?"medium":"large";}
function isHandicap(r:Row){return/handicap|nursery/i.test(`${r.features.raceName} ${r.features.raceType}`);} function isNovice(r:Row){return/novice|maiden/i.test(`${r.features.raceName} ${r.features.raceType}`);} function settled(r:Row){return r.outcome.resultStatus!=="non_runner"&&r.outcome.finishingPosition!==null;} function id(r:Row){return r.features.targetRunnerId;} function valid(v:number|null|undefined):v is number{return v!==null&&v!==undefined&&Number.isFinite(v);} function compare(a:Row,b:Row){return a.features.raceDateTime.getTime()-b.features.raceDateTime.getTime()||id(a).localeCompare(id(b));}
function group<T>(a:T[],get:(x:T)=>string){const m=new Map<string,T[]>();for(const x of a){const k=get(x);m.set(k,[...(m.get(k)??[]),x]);}return m;} function count<T>(a:T[],p:(x:T)=>boolean){return a.filter(p).length;} function distinct<T>(a:T[],get:(x:T)=>string){return new Set(a.map(get)).size;} function rate(a:number,b:number){return b?a/b:null;} function quantile(a:number[],q:number){if(!a.length)return 0;const i=(a.length-1)*q,l=Math.floor(i),u=Math.ceil(i);return l===u?a[l]!:a[l]!*(u-i)+a[u]!*(i-l);} function rankVals(a:number[]){const z=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v||x.i-y.i),o=Array<number>(a.length);for(let i=0;i<z.length;){let j=i+1;while(j<z.length&&z[j]!.v===z[i]!.v)j++;for(let k=i;k<j;k++)o[z[k]!.i]=(i+1+j)/2;i=j;}return o;} function pearson(a:number[],b:number[]){if(a.length<2)return null;const ax=a.reduce((s,x)=>s+x,0)/a.length,bx=b.reduce((s,x)=>s+x,0)/b.length;let n=0,x=0,y=0;for(let i=0;i<a.length;i++){const p=a[i]!-ax,q=b[i]!-bx;n+=p*q;x+=p*p;y+=q*q;}return x&&y?n/Math.sqrt(x*y):null;}
function find(es:Eval[],y:Year,f:Family,l:string){const e=es.find(x=>x.year===y&&x.family===f&&x.label===l);if(!e)throw new Error(`Missing ${y}/${f}/${l}`);return e;} function atLeast(a:number|null,b:number|null){return a!==null&&b!==null&&a>=b;} function pct(v:number|null){return v===null||!Number.isFinite(v)?"-":`${(v*100).toFixed(2)}%`;} function num(v:number|null){return v===null||!Number.isFinite(v)?"-":v.toFixed(3);} function table(lines:string[],rows:Record<string,unknown>[]){if(!rows.length){lines.push("No rows.","");return;}const h=Object.keys(rows[0]!);lines.push(`| ${h.join(" | ")} |`,`| ${h.map(()=>"---").join(" | ")} |`,...rows.map(r=>`| ${h.map(k=>String(r[k]??"-").replace(/\|/g,"\\|")).join(" | ")} |`),"");}

await main();
